df.describe()
pd.InfoFrame()
df_to.filetype(filename)
df.head()
df.tail()
df.info()
df.value_counts(dropna=False)
df.describe()
df.mean()
df.corr()
df.count()
df.max()
df.min()
df.median()
df.std()
df.append(df2)
df.concat(df1, df2, axis=1)
df.join(df2, on=col1, how='inner')
